### PR TITLE
Update to serde 1.0 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by nox** [comment]
I don't think you need a range here, given it's not a publicly-exposed dependency.

**Comment by Eijebong** [comment]
Do you want me to force serde 1.0 and bump it to 0.4.0 ?

**Comment by nox** [comment]
No I was saying you can force it to 1.0 and still bump to 0.3.2. But let's wait for @nagisa's opinion.

**Comment by nagisa** [comment]
Does servo use this library directly? I believe servo uses it via libloading only, which was recently updated to not depend on this library at all.

I would recommend updating servo’s dependency on libloading to 0.4 (the only other difference from 0.3 series is the requirement for a [newer rust version](https://docs.rs/libloading/0.4.0/libloading/changelog/r0_4_0/index.html), which should not be a problem for servo.).

**Comment by nox** [comment]
@nagisa I am currently doing just that, should have mentioned it here sorry.

**Comment by nagisa** [comment]
@nox ping me if the upgrade here is still necessary, please.

**Comment by Eijebong** [comment]
OK, this isn't needed anymore,

**Pull request closed without merging**
